### ISSUE TITLE
Can't disable anonymous access

### ISSUE THREAD

**Issue by SahAssar** [streamaserver/streama#1000]
### Issue description

I can't disable anonymous access

### Steps to Reproduce

I'm sorta guessing, but I think this is it:

1. Enable "Allow anonymous access"
2. Have some anonymous viewing done
3. Try to disable the "Allow anonymous access" setting

### Expected Behaviour
It should disable the "Allow anonymous access" setting

### Actual Behaviour
It silently fails (no error message in the UI), and on reload the "Allow anonymous access" setting is still enabled

### Environment Information

- **Operating System**: Arch linux
- **Streama version**: 1.9.1
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: N/A
- **Container Version (If Applicable):** Spring Boot v1.4.4.RELEASE, Spring v4.3.6.RELEASE

### Stacktrace:

```
 ERROR org.grails.web.errors.GrailsExceptionResolver - JdbcSQLException occurred when processing request: [POST] /settings/updateMultiple.json
 Referential integrity constraint violation: "FKCHS1EKH1W5YMCC8U6Q04SDCNN: PUBLIC.VIEWING_STATUS FOREIGN KEY(PROFILE_ID) REFERENCES PUBLIC.PROFILE(ID) (66)"; SQL statement:
 delete from profile where id=? and version=? [23503-193]. Stacktrace follows:
 org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
         at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:241)
         at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:755)
         at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:590)
         at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
         at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
         at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
         at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
         at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
         at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
         at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
         at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
         at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
 Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
         at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
         at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
         at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
         at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
         at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
         at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
         at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3244)
         at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3481)
         at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:98)
         at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
         at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
         at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
         at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
         at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
         at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:468)
         at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3135)
         at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2352)
         at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:491)
         at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147)
         at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
         at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
         at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
         at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:582)
         ... 40 common frames omitted
 Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FKCHS1EKH1W5YMCC8U6Q04SDCNN: PUBLIC.VIEWING_STATUS FOREIGN KEY(PROFILE_ID) REFERENCES PUBLIC.PROFILE(ID) (66)"; SQL statement:
 delete from profile where id=? and version=? [23503-193]
         at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
         at org.h2.message.DbException.get(DbException.java:179)
         at org.h2.message.DbException.get(DbException.java:155)
         at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:426)
         at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:443)
         at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:318)
         at org.h2.table.Table.fireConstraints(Table.java:967)
         at org.h2.table.Table.fireAfterRow(Table.java:985)
         at org.h2.command.dml.Delete.update(Delete.java:101)
         at org.h2.command.CommandContainer.update(CommandContainer.java:98)
         at org.h2.command.Command.executeUpdate(Command.java:258)
         at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
         at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
         at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
```

**Comment by arindammitra06** [comment]
If you are using mysql DB, you have to manually update the table 'Settings' for id=8.
But remember to set the value as 'false' not false as boolean.

**Comment by SahAssar** [comment]
This was using the default H2 db, not mysql.
