### ISSUE TITLE
Error adding TV show to watchlist: Cannot get property 'id' on null object

### ISSUE THREAD

**Issue by johnsmith1232541** [streamaserver/streama#1091]
### Issue description
After creating a TV show, I cannot add the TV show to watchlist, it gives an internal server error and the entire StackTrace is below.

### Steps to Reproduce

1. Create TV show
2. Add TV show to watchlist
3. ERROR

### StackTrace
```
ERROR StackTrace - Full Stack Trace:
Oct 29 22:34:18 movies streama.jar[2740]: org.grails.web.converters.exceptions.ConverterException: java.lang.NullPointerException: Cannot get property 'id' on null object
Oct 29 22:34:18 movies streama.jar[2740]:         at org.grails.web.converters.marshaller.ClosureObjectMarshaller.marshalObject(ClosureObjectMarshaller.java:65)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.converters.JSON.value(JSON.java:184)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.converters.JSON.render(JSON.java:119)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.converters.JSON.render(JSON.java:132)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:190)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.artefact.controller.support.ResponseRenderer$Trait$Helper$render.call(Unknown Source)
Oct 29 22:34:18 movies streama.jar[2740]:         at streama.WatchlistEntryController.render(WatchlistEntryController.groovy)
Oct 29 22:34:18 movies streama.jar[2740]:         at sun.reflect.GeneratedMethodAccessor570.invoke(Unknown Source)
Oct 29 22:34:18 movies streama.jar[2740]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Oct 29 22:34:18 movies streama.jar[2740]:         at java.lang.reflect.Method.invoke(Method.java:498)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
Oct 29 22:34:18 movies streama.jar[2740]:         at streama.WatchlistEntryController$__tt__create_closure7.doCall(WatchlistEntryController.groovy:45)
Oct 29 22:34:18 movies streama.jar[2740]:         at streama.WatchlistEntryController$__tt__create_closure7.doCall(WatchlistEntryController.groovy)
Oct 29 22:34:18 movies streama.jar[2740]:         at sun.reflect.GeneratedMethodAccessor1175.invoke(Unknown Source)
Oct 29 22:34:18 movies streama.jar[2740]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Oct 29 22:34:18 movies streama.jar[2740]:         at java.lang.reflect.Method.invoke(Method.java:498)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.Closure.call(Closure.java:414)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.Closure.call(Closure.java:408)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.converters.JSON.use(JSON.java:384)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.converters.JSON$use.call(Unknown Source)
Oct 29 22:34:18 movies streama.jar[2740]:         at streama.WatchlistEntryController.$tt__create(WatchlistEntryController.groovy:44)
Oct 29 22:34:18 movies streama.jar[2740]:         at streama.WatchlistEntryController$_create_closure1.doCall(WatchlistEntryController.groovy)
Oct 29 22:34:18 movies streama.jar[2740]:         at sun.reflect.GeneratedMethodAccessor1035.invoke(Unknown Source)
Oct 29 22:34:18 movies streama.jar[2740]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Oct 29 22:34:18 movies streama.jar[2740]:         at java.lang.reflect.Method.invoke(Method.java:498)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.Closure.call(Closure.java:414)
Oct 29 22:34:18 movies streama.jar[2740]:         at groovy.lang.Closure.call(Closure.java:430)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
Oct 29 22:34:18 movies streama.jar[2740]:         at streama.WatchlistEntryController.create(WatchlistEntryController.groovy)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
Oct 29 22:34:18 movies streama.jar[2740]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
Oct 29 22:34:18 movies streama.jar[2740]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Oct 29 22:34:18 movies streama.jar[2740]:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
```

**Comment by agustinpallares94** [comment]
hello!!
I have the same problem.
Have you achieved to solve this problem?

**Comment by darkarp** [comment]
> hello!!
> 
> I have the same problem.
> 
> Have you achieved to solve this problem?

Hi! I ended up fixing it myself and adding a pull request: https://github.com/streamaserver/streama/pull/1092

It should fix this issue :)

**Comment by agustinpallares94** [comment]
Yeeeeessss, this worked for me. Thank you so much!!

**Comment by agustinpallares94** [comment]
> > hello!!
> > I have the same problem.
> > Have you achieved to solve this problem?
> 
> Hi! I ended up fixing it myself and adding a pull request: #1092
> 
> It should fix this issue :)
Yeeeeessss, this worked for me. Thank you so much!!

**Comment by darkarp** [comment]
No worries, glad it helped :)

**Comment by darkarp** [comment]
> > > hello!!
> 
> > > I have the same problem.
> 
> > > Have you achieved to solve this problem?
> 
> > 
> 
> > Hi! I ended up fixing it myself and adding a pull request: #1092
> 
> > 
> 
> > It should fix this issue :)
> 
> Yeeeeessss, this worked for me. Thank you so much!!
> 
> 

No worries, glad it helped :)
