### ISSUE TITLE
Internal Server Error when Bulk-creating from files when there is an improperly formatted filename

### ISSUE THREAD

**Issue by EMcCormack** [streamaserver/streama#663]
### Issue description
When selecting Bulk-Create from file(s) option on the Streama web-app, I am hit with an Internal Server Error. This is due to an improperly formatted folder/file name in Windows (ends with a period). In this specific case, it's a folder called "The O.C.". 

### Steps to Reproduce

1. Create a folder that ends with a period (can't be done in a Windows environment). I did this by creating the folder on my external HDD on my linux environment.
2. Set the local path for files to be a parent directory of the improperly formatted folder.
3. Select Bulk-Create from file(s) from the "Manage Content" option. When selecting the parent-folder of the improperly-formatted folder, an internal server error will occur.

### Expected Behaviour
Either the improperly-formatted folder will be ignored and the rest of the results will be displayed, or there will be an error message to indicate the error occured.

### Actual Behaviour

Internal Server Error occurred pop-up message in UI
Stacktrace:
ERROR org.grails.web.errors.GrailsExceptionResolver - NoSuchFileException occurred when processing request: [GET] /file/localFiles.json - parameters:
path: D:\Videos\TV Shows
D:\Videos\TV Shows\The O.C.. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: D:\Videos\TV Shows\The O.C.
	at java.nio.file.Files.isHidden(Files.java:1531)
	at streama.FileController$_localFiles_closure9.doCall(FileController.groovy:277)
	at streama.FileController.localFiles(FileController.groovy:275)
	... 36 common frames omitted

### Environment Information

- **Operating System**: Windows 10
- **Streama version**:  c41d41c
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

**Comment by EMcCormack** [comment]
This can be resolved by ignoring the improperly-formatted folder or file by adding a try-catch statement in FileController.groovy at the bottom of localFiles(String path)

````
     def response = []
     Files.list(dirPath).each { file ->
      try {
        if (Files.isHidden(file)) {
          return
        }
        response << [
          name     : file.getFileName().toString(),
          path     : file.toAbsolutePath().toString(),
          directory: Files.isDirectory(file)
        ]
      } catch (ignored) {
      }
    }
    render response as JSON
````

Not sure if this is the best solution though

**Comment by EMcCormack** [comment]
Hmmm, not sure. I could try to break it in Linux too later ;)
Error would probably be best
