### ISSUE TITLE
Cant watch movie

### ISSUE THREAD

**Issue by DrEthan77** [streamaserver/streama#670]
### Issue description
i have been trying to launch streama for a while and i finnaly got the install and website setup, however after i upload a movie and then push play it says internal server error and then it displays this
ERROR org.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /video/show.json
Cannot invoke method getSimpleInstance() on null object. Stacktrace follows:

### Steps to Reproduce

1. install streama like normal
2. open it in browser and set it up with defaults
3.  upload movie
4. try to play

### Expected Behaviour

movie play

### Actual Behaviour

nothing except internal server error in bottom right

### Environment Information

- **Operating System**:  ubuntu (latest)
- **Streama version**: 1.6.0 RC8

### Example Application / access to your live versio
here is the stack trace

`ERROR org.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /video/show.json
Cannot invoke method getSimpleInstance() on null object. Stacktrace follows:
org.grails.web.converters.exceptions.ConverterException: java.lang.NullPointerException: Cannot invoke method getSimpleInstance() on null object
	at org.grails.web.converters.marshaller.ClosureObjectMarshaller.marshalObject(ClosureObjectMarshaller.java:65)
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.render(JSON.java:119)
	at grails.converters.JSON.render(JSON.java:132)
	at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:190)
	at streama.VideoController$_show_closure4.doCall(VideoController.groovy:100)
	at grails.converters.JSON.use(JSON.java:384)
	at streama.VideoController.show(VideoController.groovy:99)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Cannot invoke method getSimpleInstance() on null object
	at streama.marshallers.PlayerMarshallerService$__tt__init_closure2$_closure3.doCall(PlayerMarshallerService.groovy:67)
	at org.grails.web.converters.marshaller.ClosureObjectMarshaller.marshalObject(ClosureObjectMarshaller.java:50)
	... 46 common frames omitted `

**Comment by Jeronimo95** [comment]
@dularion this looks like an issue relating to the next episode feature. Doesn't happen in rc7. I haven't had a chance to test myself yet though.

**Comment by AciDCooL** [comment]
Maybe an idea, but give this docker image a try, its not persistent so you won't have old database issues, and no installation issues since all dependencies are in the image. https://hub.docker.com/r/gkiko/streama/
This way you can make sure it's nothing system related. And it maybe helps if we knew the file (mkv, mp4?) and or format (codec etc) you are playing?

**Comment by DrEthan77** [comment]
K I'll try that when i get home, and I am using a mpv4 with web support from handbrake which rips straight from a disk

**Comment by adamgiesinger** [comment]
I'm having the same problem using RC8 aswell.

**Comment by DrEthan77** [comment]
yeah the docker didnt work either

**Comment by adamgiesinger** [comment]
RC7 works for me! 👍

**Comment by Jeronimo95** [comment]
Yeah looks like RC8 is bugged, I'm going to remove it from the releases and we'll look into it.

**Comment by AciDCooL** [comment]
I reencoded a file to h264 with aac in mp4 format (max compat) and tested with localpath and upload. Localpath is fine, upload give internal error like DrEthan77 said. Funny part is the preview function works with the uploaded file, and the download on the preview player works as well.

**Comment by dularion** [comment]
thanks for that, ill check out RC8 and see what the cause is

**Comment by dularion** [comment]
alright, here u go :) try it out https://github.com/streamaserver/streama/releases/tag/v1.6.0-RC9

**Comment by agustinpallares94** [comment]
I have the same error, how did you solve it?
