### ISSUE TITLE
OutofMemory

### ISSUE THREAD

**Issue by allanf181** [streamaserver/streama#712]
### Issue description
Outofmemory playing avi file. (-Xmx3g)

### Steps to Reproduce

1. Add an avi file

### Expected Behaviour

Play file

### Actual Behaviour

![image](https://user-images.githubusercontent.com/14101716/50486001-e15f0000-09de-11e9-8b47-c4d080f3839d.png)
```
        at org.springframework.http.converter.AbstractGenericHttpMessageConverte
r.write(AbstractGenericHttpMessageConverter.java:100)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessage
ConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMeth
odProcessor.java:231)
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMetho
dProcessor.handleReturnValue(HttpEntityMethodProcessor.java:203)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandle
rComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:846)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(Pag
eFragmentCachingFilter.java:196)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter
.java:63)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(Gr
ailsWebRequestFilter.java:77)
Caused by: java.io.IOException: Uma conexÒo estabelecida foi anulada pelo softwa
re no computador host
        ... 20 common frames omitted
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDis
patcherServlet] - Servlet.service() for servlet grailsDispatcherServlet threw ex
ception
java.lang.IllegalStateException: getOutputStream() has already been called for t
his response
        at org.apache.catalina.connector.Response.getWriter(Response.java:609)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade
.java:211)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper
.java:109)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper
.java:109)
        at org.grails.web.servlet.mvc.OutputAwareHttpServletResponse.getWriter(O
utputAwareHttpServletResponse.groovy:28)
        at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(Ge
nericGroovyTemplateView.groovy:69)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView
.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherSe
rvlet.java:1271)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResu
lt(DispatcherServlet.java:1037)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:980)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(Pag
eFragmentCachingFilter.java:196)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter
.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(Gr
ailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDisp
atcher.java:726)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationD
ispatcher.java:592)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDis
patcher.java:526)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.j
ava:389)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.j
ava:254)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValv
e.java:349)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:175)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java
:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Unknown Source)
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] - Exception Pr
ocessing ErrorPage[errorCode=0, location=/error]
javax.servlet.ServletException: org.springframework.web.util.NestedServletExcept
ion: Request processing failed; nested exception is java.lang.IllegalStateExcept
ion: getOutputStream() has already been called for this response
        at grails.plugin.cache.web.filter.AbstractFilter.logThrowable(AbstractFi
lter.java:116)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter
.java:70)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(Gr
ailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDisp
atcher.java:726)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationD
ispatcher.java:592)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDis
patcher.java:526)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.j
ava:389)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.j
ava:254)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValv
e.java:349)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:175)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java
:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.web.util.NestedServletException: Request processi
ng failed; nested exception is java.lang.IllegalStateException: getOutputStream(
) has already been called for this response
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:982)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:165)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(Pag
eFragmentCachingFilter.java:196)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter
.java:63)
        ... 40 common frames omitted
Caused by: java.lang.IllegalStateException: getOutputStream() has already been c
alled for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:609)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade
.java:211)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper
.java:109)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper
.java:109)
        at org.grails.web.servlet.mvc.OutputAwareHttpServletResponse.getWriter(O
utputAwareHttpServletResponse.groovy:28)
        at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(Ge
nericGroovyTemplateView.groovy:69)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView
.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherSe
rvlet.java:1271)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResu
lt(DispatcherServlet.java:1037)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:980)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:970)
        ... 51 common frames omitted
```

### Environment Information

- **Operating System**: Windows 7 64-bits
- **Streama version**: 1.6.0-Final
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: none
- **Container Version (If Applicable):** none

**Comment by EchoDev** [comment]
I don't think Streama supports playback of .avi files since your browser needs to support playback of it.

If you convert the file to h264 video with aac audio in a mp4 container it will work just fine. (This is easy to do with handbrake if you don't have experience with encoding videos)

**Comment by kerberjg** [comment]
I've seen a similar occurrence while playing a H264-encoded mkv file **occasionally**. In most instances it would play fine, with this happening sometimes.
