### ISSUE TITLE
 Table 'steama.user' doesn't exist

### ISSUE THREAD

**Issue by Pupwiz** [streamaserver/streama#733]
Configuring Spring Security Core ...
... finished configuring Spring Security Core

ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Table 'steama.user' doesn't exist
ERROR org.springframework.boot.SpringApplication - Application startup failed

It seems to be not creating a table when using MariaDB-MySQL 
starts fine if I don't use it but switching to the application.yml 
I get the table doesn't exist, all other tables are built 
or am I missing a step?

Server version: 10.1.37-MariaDB
Debian GNU/Linux 9.7 (stretch)

**Comment by dularion** [comment]
Hm.. is this the first time you are setting it up? What java version are you using? what mysql version? what if you drop the database and recreate and let streama start again?

**Comment by JavanWang** [comment]
I have the same issue.
streama-1.6.7(2019/06/10 download source code)
openjdk version "1.8.0_212"
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) 
application.yml:
            dbCreate: update
            driverClassName:  'com.mysql.cj.jdbc.Driver'
            url: jdbc:mysql://localhost/streama?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
            username: root
            password: mypassword

the database is totally clean and empty
I just create database streama only
after launch streama server fails, I ask tables list as 
mysql> show tables;
+---------------------+
| Tables_in_streama   |
+---------------------+
| file                |
| generic_video_genre |
| generic_video_tag   |
| genre               |
| movie_genre         |
| movie_tag           |
| notification_queue  |
| profile             |
| report              |
| role                |
| tag                 |
| tv_show             |
| tv_show_genre       |
| user_activity       |
| user_genre          |
| user_role           |
| video               |
| video_file          |
| viewing_status      |
+---------------------+

java error dump:
`ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Table 'streama.user' doesn't exist
ERROR org.springframework.boot.SpringApplication - Application startup failed
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:79)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2122)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1905)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1881)
	at org.hibernate.loader.Loader.doQuery(Loader.java:925)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2622)
	at org.hibernate.loader.Loader.doList(Loader.java:2605)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2434)
	at org.hibernate.loader.Loader.list(Loader.java:2429)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResultViaListCall(AbstractHibernateQuery.java:785)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResult(AbstractHibernateQuery.java:775)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder.invokeQuery(AbstractFindByFinder.java:35)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder$1.doInSession(AbstractFindByFinder.java:29)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:318)
	at org.grails.datastore.gorm.finders.AbstractFinder.execute(AbstractFinder.java:42)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder.doInvokeInternal(AbstractFindByFinder.java:27)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:174)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:374)
	at org.grails.datastore.gorm.finders.FinderMethod$invoke$0.call(Unknown Source)
	at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:173)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.staticMethodMissing(GormEntity.groovy:749)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$staticMethodMissing$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at streama.User.staticMethodMissing(User.groovy)
	at streama.User$staticMethodMissing.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
	at streama.User.$static_methodMissing(User.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`

**Comment by dularion** [comment]
yes this is a known issue and it was fixed in 1.7.0.i guess its time to release that version ...

**Comment by JavanWang** [comment]
I had install "streama-1.7.0-RC14" already, and struggle with "com.mysql.cj.jdbc.Driver"
you save my life timely
thank you very much
