### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by GermanCoding** [streamaserver/streama#985]
### Issue description
Since sometime around v1.9.0 (can't pinpoint the exact commit, but 1.8.3 worked for me) some tests are failing. The failing tests are:

`streama.VideoServiceSpec > test delete video and all associations`

`streama.VideoSpec > test has files, with files`

### Steps to Reproduce
1. Compile and build a recent streama version, using .`/gradlew build`

### Expected Behaviour
All tests pass

### Actual Behaviour
The tests `streama.VideoServiceSpec > test delete video and all associations` and `streama.VideoSpec > test has files, with files` fail, causing the entire build to fail.

The output is:

```
:test

streama.VideoServiceSpec > test delete video and all associations FAILED
    java.lang.VerifyError at VideoServiceSpec.groovy:9

streama.VideoSpec > test has files, with files FAILED
    java.lang.NoClassDefFoundError at VideoSpec.groovy:32

17 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/Max/streama/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Test error for `test delete video and all associations`:

```
java.lang.VerifyError: class net.sf.cglib.core.DebuggingClassWriter overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.sf.cglib.core.AbstractClassGenerator.<init>(AbstractClassGenerator.java:38)
	at net.sf.cglib.core.KeyFactory$Generator.<init>(KeyFactory.java:127)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:112)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:80)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:99)
	at streama.VideoServiceSpec.$spock_initializeFields(VideoServiceSpec.groovy:9)

```

Test error for `test has files, with files`:

```
java.lang.NoClassDefFoundError: Could not initialize class org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory$ConstructorFriendlyEnhancer
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:80)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.StubImpl(SpecInternals.java:131)
	at streama.VideoSpec.test has files, with files(VideoSpec.groovy:32)
```

### Environment Information

- **Operating System**: Windows 10 64 bit
- **Streama version**: v1.9.0 and later, tested up to current master (80f5a2f7b1b1757a9cb038a31f31cb4acfd33402)
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: I've tried a clean clone of the repo, no customizations done
- **Container Version (If Applicable):** N/A

**Comment by daknin** [comment]
0e52a040 added a dependency on org.apache.tika:tika-parsers:1.12 that has updated `org.ow2.asm:asm:5.0.3` to `org.ow2.asm:asm:5.0.4`

Excluding the dependency in build.gradle fixes the failing tests:
```
  compile ("org.apache.tika:tika-parsers:1.12") {
    exclude group: 'org.ow2.asm', module: 'asm'
}
```

However, `org.apache.tika:tika-parsers` also brings in numerous dependencies for parsing non video files (Access, Excel, PDF, CDF.....), which can probably also be excluded
```
\--- org.apache.tika:tika-parsers:1.12
     +--- org.apache.tika:tika-core:1.12
     +--- org.gagravarr:vorbis-java-tika:0.6
     |    \--- org.apache.tika:tika-core:1.5 -> 1.12
     +--- com.healthmarketscience.jackcess:jackcess:2.1.2
     |    +--- commons-lang:commons-lang:2.6
     |    \--- commons-logging:commons-logging:1.1.3 -> 1.2
     +--- com.healthmarketscience.jackcess:jackcess-encrypt:2.1.1
     |    +--- com.healthmarketscience.jackcess:jackcess:2.1.0 -> 2.1.2 (*)
     |    \--- org.bouncycastle:bcprov-jdk15on:1.52
     +--- net.sourceforge.jmatio:jmatio:1.0
     +--- org.apache.james:apache-mime4j-core:0.7.2
     +--- org.apache.james:apache-mime4j-dom:0.7.2
     |    \--- org.apache.james:apache-mime4j-core:0.7.2
     +--- org.apache.commons:commons-compress:1.10
     +--- org.tukaani:xz:1.5
     +--- commons-codec:commons-codec:1.9 -> 1.10
     +--- org.apache.pdfbox:pdfbox:1.8.10
     |    +--- org.apache.pdfbox:fontbox:1.8.10
     |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
     |    +--- org.apache.pdfbox:jempbox:1.8.10
     |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
     +--- org.bouncycastle:bcmail-jdk15on:1.52
     |    +--- org.bouncycastle:bcprov-jdk15on:1.52
     |    \--- org.bouncycastle:bcpkix-jdk15on:1.52
     |         \--- org.bouncycastle:bcprov-jdk15on:1.52
     +--- org.bouncycastle:bcprov-jdk15on:1.52
     +--- org.apache.poi:poi:3.13
     |    \--- commons-codec:commons-codec:1.9 -> 1.10
     +--- org.apache.poi:poi-scratchpad:3.13
     |    \--- org.apache.poi:poi:3.13 (*)
     +--- org.apache.poi:poi-ooxml:3.13
     |    +--- org.apache.poi:poi:3.13 (*)
     |    \--- org.apache.poi:poi-ooxml-schemas:3.13
     |         \--- org.apache.xmlbeans:xmlbeans:2.6.0
     +--- org.ccil.cowan.tagsoup:tagsoup:1.2.1
     +--- org.ow2.asm:asm:5.0.4
     +--- com.googlecode.mp4parser:isoparser:1.0.2
     |    \--- org.aspectj:aspectjrt:1.8.0 -> 1.8.9
     +--- com.drewnoakes:metadata-extractor:2.8.0
     |    \--- com.adobe.xmp:xmpcore:5.1.2
     +--- de.l3s.boilerpipe:boilerpipe:1.1.0
     +--- com.rometools:rome:1.5.1
     |    +--- com.rometools:rome-utils:1.5.1
     |    +--- org.jdom:jdom:2.0.2
     |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.22
     +--- org.gagravarr:vorbis-java-core:0.6
     +--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
     +--- org.codelibs:jhighlight:1.0.2
     +--- com.pff:java-libpst:0.8.1
     +--- com.github.junrar:junrar:0.7
     |    +--- commons-logging:commons-logging-api:1.1
     |    \--- org.apache.commons:commons-vfs2:2.0
     |         +--- commons-logging:commons-logging:1.1.1 -> 1.2
     |         +--- org.apache.maven.scm:maven-scm-api:1.4
     |         |    \--- org.codehaus.plexus:plexus-utils:1.5.6
     |         \--- org.apache.maven.scm:maven-scm-provider-svnexe:1.4
     |              +--- org.apache.maven.scm:maven-scm-provider-svn-commons:1.4
     |              |    +--- org.apache.maven.scm:maven-scm-api:1.4 (*)
     |              |    \--- org.codehaus.plexus:plexus-utils:1.5.6
     |              +--- regexp:regexp:1.3
     |              +--- org.apache.maven.scm:maven-scm-api:1.4 (*)
     |              \--- org.codehaus.plexus:plexus-utils:1.5.6
     +--- org.apache.cxf:cxf-rt-rs-client:3.0.3
     |    +--- org.apache.cxf:cxf-rt-transports-http:3.0.3
     |    |    \--- org.apache.cxf:cxf-core:3.0.3
     |    |         +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
     |    |         |    \--- org.codehaus.woodstox:stax2-api:3.1.4
     |    |         \--- org.apache.ws.xmlschema:xmlschema-core:2.1.0
     |    +--- org.apache.cxf:cxf-core:3.0.3 (*)
     |    \--- org.apache.cxf:cxf-rt-frontend-jaxrs:3.0.3
     |         +--- org.apache.cxf:cxf-core:3.0.3 (*)
     |         +--- javax.ws.rs:javax.ws.rs-api:2.0.1
     |         +--- javax.annotation:javax.annotation-api:1.2
     |         \--- org.apache.cxf:cxf-rt-transports-http:3.0.3 (*)
     +--- org.apache.opennlp:opennlp-tools:1.5.3
     |    +--- org.apache.opennlp:opennlp-maxent:3.0.3
     |    \--- net.sf.jwordnet:jwnl:1.3.3
     +--- commons-io:commons-io:2.4
     +--- org.apache.commons:commons-exec:1.3
     +--- com.googlecode.json-simple:json-simple:1.1.1
     +--- org.json:json:20140107
     +--- com.google.code.gson:gson:2.2.4 -> 2.7
     +--- edu.ucar:netcdf4:4.5.5
     |    +--- edu.ucar:cdm:4.5.5
     |    |    +--- edu.ucar:udunits:4.5.5
     |    |    |    +--- joda-time:joda-time:2.2 -> 2.9.7
     |    |    |    \--- net.jcip:jcip-annotations:1.0
     |    |    +--- edu.ucar:httpservices:4.5.5
     |    |    |    +--- net.jcip:jcip-annotations:1.0
     |    |    |    +--- org.apache.httpcomponents:httpclient:4.2.6 -> 4.5.2
     |    |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.6
     |    |    |    |    +--- commons-logging:commons-logging:1.2
     |    |    |    |    \--- commons-codec:commons-codec:1.9 -> 1.10
     |    |    |    +--- org.apache.httpcomponents:httpcore:4.2.5 -> 4.4.6
     |    |    |    +--- org.apache.httpcomponents:httpmime:4.2.6 -> 4.5.2
     |    |    |    |    \--- org.apache.httpcomponents:httpclient:4.5.2 (*)
     |    |    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.22
     |    |    +--- org.apache.httpcomponents:httpcore:4.2.5 -> 4.4.6
     |    |    +--- joda-time:joda-time:2.2 -> 2.9.7
     |    |    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.22
     |    |    +--- org.jdom:jdom2:2.0.4 -> 2.0.6
     |    |    +--- net.jcip:jcip-annotations:1.0
     |    |    +--- org.quartz-scheduler:quartz:2.2.0
     |    |    |    +--- c3p0:c3p0:0.9.1.1
     |    |    |    \--- org.slf4j:slf4j-api:1.6.6 -> 1.7.22
     |    |    +--- com.google.protobuf:protobuf-java:2.5.0
     |    |    +--- net.sf.ehcache:ehcache-core:2.6.2
     |    |    |    \--- org.slf4j:slf4j-api:1.6.1 -> 1.7.22
     |    |    +--- com.google.guava:guava:17.0
     |    |    +--- org.itadaki:bzip2:0.9.1
     |    |    +--- com.beust:jcommander:1.35
     |    |    \--- org.slf4j:jcl-over-slf4j:1.7.7 -> 1.7.22 (*)
     |    +--- net.jcip:jcip-annotations:1.0
     |    +--- net.java.dev.jna:jna:4.1.0 -> 4.2.2
     |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.22
     +--- edu.ucar:grib:4.5.5
     |    +--- edu.ucar:cdm:4.5.5 (*)
     |    +--- com.google.protobuf:protobuf-java:2.5.0
     |    +--- org.jdom:jdom2:2.0.4 -> 2.0.6
     |    +--- org.jsoup:jsoup:1.7.2
     |    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.22
     |    +--- net.jcip:jcip-annotations:1.0
     |    +--- edu.ucar:jj2000:5.2
     |    \--- org.itadaki:bzip2:0.9.1
     +--- edu.ucar:cdm:4.5.5 (*)
     +--- edu.ucar:httpservices:4.5.5 (*)
     +--- org.apache.commons:commons-csv:1.0
     +--- org.apache.sis.core:sis-utility:0.5
     |    \--- org.opengis:geoapi:3.0.0
     |         \--- javax.measure:jsr-275:0.9.3
     +--- org.apache.sis.storage:sis-netcdf:0.5
     |    +--- org.apache.sis.storage:sis-storage:0.5
     |    |    +--- org.apache.sis.core:sis-metadata:0.5
     |    |    |    +--- org.apache.sis.core:sis-utility:0.5 (*)
     |    |    |    \--- org.opengis:geoapi:3.0.0 (*)
     |    |    +--- org.apache.sis.core:sis-referencing:0.5
     |    |    |    +--- org.apache.sis.core:sis-utility:0.5 (*)
     |    |    |    +--- org.apache.sis.core:sis-metadata:0.5 (*)
     |    |    |    \--- org.opengis:geoapi:3.0.0 (*)
     |    |    \--- org.opengis:geoapi:3.0.0 (*)
     |    +--- org.apache.sis.core:sis-metadata:0.5 (*)
     |    +--- org.apache.sis.core:sis-referencing:0.5 (*)
     |    \--- org.opengis:geoapi:3.0.0 (*)
     +--- org.apache.sis.core:sis-metadata:0.5 (*)
     \--- org.opengis:geoapi:3.0.0 (*)
```

**Comment by dularion** [comment]
Thanks guys! This is resolved now
