### ISSUE TITLE
Unable to find DataSource.groovy

### ISSUE THREAD

**Issue by arindammitra06** [streamaserver/streama#989]
Hi,

Thanks for this beautiful project. I was trying to setup MySQL locally but my installation doesn't allow me to create root user without password. Hence I wanted to change the password as you mentioned in DataSource.groovy. But in the current project I couldn't find the DataSource.groovy. I tried changing in application.yml but everytime i get the below exception. I am able to connect from MySQL client.

`ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)`

**Comment by dularion** [comment]
hi, see this for guidance. if that doesnt get you started, let us know: https://docs.streama-project.com/config/databases/

**Comment by arindammitra06** [comment]
Thanks for your reply. This issue was just because of the latest version of mysql, got resolved once i downgraded to the 5.7 i guess.. thanks anyway...
